#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "---> ACTION HOOK: deploy <---"
source $OPENSHIFT_HOMEDIR/python/virtenv/venv/bin/activate

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"/manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"/manage.py collectstatic --noinput

# TODO: Not needed in the end
echo "Executing 'npm install less'"
#touch $OPENSHIFT_DATA_DIR/.env
#echo $NPM_CONFIG_USERCONFIG
NPM_CONFIG_USERCONFIG="$OPENSHIFT_HOMEDIR"/app-root/build-dependencies/.npmrc npm install less
