#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "---> ACTION HOOK: deploy <---"

echo "Symlink media directory"
if [ ! -d ${OPENSHIFT_DATA_DIR}media ]; then
mkdir ${OPENSHIFT_DATA_DIR}media
fi
ln -sf ${OPENSHIFT_DATA_DIR}media ${OPENSHIFT_REPO_DIR}wsgi/static/media

echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py migrate --noinput'"
python ${OPENSHIFT_REPO_DIR}manage.py migrate --noinput

# Not needed since installed less is pushed
# ${OPENSHIFT_REPO_DIR}/scripts/os_install_less

echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py collectstatic --noinput'"
python ${OPENSHIFT_REPO_DIR}manage.py collectstatic --noinput

echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py compress'"
python ${OPENSHIFT_REPO_DIR}manage.py compress

echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py create_appcache_manifest'"
python ${OPENSHIFT_REPO_DIR}manage.py create_appcache_manifest
