#!/bin/bash
# Recreate SQLite database with superuser and configuration
if [ ${OPENSHIFT_REPO_DIR:+x} ]
then
	APP_DIR=$OPENSHIFT_REPO_DIR
else
	APP_DIR="$(dirname "$(cd "$(dirname "$0" )"; pwd)" )"
fi
cd $APP_DIR

rm -f $APP_DIR/db.sqlite3
rm -fr $APP_DIR/media/*

$APP_DIR/manage.py migrate --noinput

echo "from main.factories import create_superuser; create_superuser()" | ./manage.py shell
echo "from main.factories import create_staff; create_staff()" | ./manage.py shell
echo "from ropeelements.factories import create_config; create_config()" | ./manage.py shell
