#!/bin/bash
# Recreate SQLite database with superuser and configuration
if [ ${OPENSHIFT_REPO_DIR:+x} ]
then
	APP_DIR=$OPENSHIFT_REPO_DIR
	DATA_DIR=$OPENSHIFT_DATA_DIR
	MEDIA_DIR=$DATA_DIR
else
	APP_DIR="$(dirname "$(cd "$(dirname "$0" )"; pwd)" )"
	DATA_DIR=$APP_DIR
	MEDIA_DIR=$DATA_DIR/static
fi
cd $APP_DIR

rm -f $DATA_DIR/db.sqlite3
rm -fr $MEDIA_DIR/media/*

$APP_DIR/manage.py migrate --noinput

echo "from main.factories import create_superuser; create_superuser()" | ./manage.py shell
echo "from main.factories import create_staff; create_staff()" | ./manage.py shell
echo "from ropeelements.factories import create_config; create_config()" | ./manage.py shell
echo "from ropeelements.factories import create_difficulties; create_difficulties()" | ./manage.py shell
