#!/bin/bash
echo "Install less"

echo "node `node --version`"
echo "npm `npm --version`"

echo "Configuring npm cache"
export NPM_CONFIG_USERCONFIG=${OPENSHIFT_HOMEDIR}app-root/build-dependencies/.npmrc
cd ${OPENSHIFT_HOMEDIR}app-root/build-dependencies
npm config set cache ${OPENSHIFT_HOMEDIR}app-root/build-dependencies/.npm

echo "Executing 'npm install less@1.7.0 --prefix $OPENSHIFT_REPO_DIR'"
npm install less@1.7.0 --prefix $OPENSHIFT_REPO_DIR
