#!/bin/bash
# Recreate SQLite database with sample data
if [ ${OPENSHIFT_REPO_DIR:+x} ]
then
	APP_DIR=$OPENSHIFT_REPO_DIR
else
	APP_DIR="$(dirname "$(cd "$(dirname "$0" )"; pwd)" )"
fi

$APP_DIR/scripts/create_db
$APP_DIR/scripts/create_sample.py
